{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubepilot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubepilot.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ required "A jwtSecret is required" .Values.secret.jwtSecret | b64enc | quote }}
  {{- if .Values.admin.password }}
  admin-password: {{ .Values.admin.password | b64enc | quote }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubepilot.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubepilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.externalPostgresql.enabled }}
  connection-string: {{ printf "postgres://%s@%s:%d/%s" .Values.externalPostgresql.username .Values.externalPostgresql.host (.Values.externalPostgresql.port | int) .Values.externalPostgresql.database | quote }}
  {{- else }}
  connection-string: {{ printf "postgres://%s:%s@%s-postgresql:5432/%s?sslmode=disable" .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Values.postgresql.auth.database | quote }}
  {{- end }}
